runtime: python310  # Use Python 3.10 for compatibility
entrypoint: gunicorn -b :$PORT app:app  # Use Gunicorn to run Flask app

env_variables:
  FLASK_APP: "app.py"
  FLASK_ENV: "production"  # Set to production for the live environment
  FLASK_DEBUG: "0"
  GOOGLE_CLOUD_PROJECT: "healthcaresys2024"  # Google cloud project ID

handlers:
  - url: /static
    static_dir: static/  # Ensure your static files are correctly located
  - url: /.*
    script: auto  # Direct all other routes to the app
