runtime: python39  # Python 3.9 is more stable for App Engine

entrypoint: gunicorn -b :$PORT app:app  # Use gunicorn to run Flask app

env_variables:
  FLASK_APP: "app.py"
  FLASK_ENV: "development"
  FLASK_DEBUG: "0"
  GOOGLE_CLOUD_PROJECT: "healthcaresys2024"  # Google cloud project ID

handlers:
  - url: /static
    static_dir: static/  # Ensure your static files are correctly located
  - url: /.*  
    script: auto  # Direct all other routes to the app
