runtime: custom
env: flex  # Flexible environment

env_variables:
  FLASK_APP: "app.py"
  FLASK_ENV: "production"
  GOOGLE_CLOUD_PROJECT: "healthcaresys2024"  # your project ID

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto
