steps:
  # Step 1: Install system dependencies for dbus, cmake, and pkg-config
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y \
        libdbus-1-dev \
        cmake \
        pkg-config \
        dbus-1

  # Step 2: Set up the Python environment and install dependencies
  - name: 'gcr.io/cloud-builders/python'
    args:
      - 'pip'
      - 'install'
      - '-r'
      - 'requirements.txt'

  # Step 3: Deploy to Google App Engine
  - name: 'gcr.io/google-appengine/python'
    args:
      - 'gcloud'
      - 'app'
      - 'deploy'
      - '--quiet'

# Define substitution variables if needed for dynamic values like versions, project id, etc.
substitutions:
  _APP_NAME: 'healthcaresys2024'
  _GCP_PROJECT_ID: 'healthcaresys2024'

# Timeout to ensure the build doesn't hang indefinitely
timeout: '600s'

# Available Build Resources can be specified if needed, like the memory and CPU allocated
availableMemoryMb: 2048
